// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicPropertiesLayoutSection,
  DefaultPropertiesLayoutSectionProps
} from "./plasmic/flutter_builder/PlasmicPropertiesLayoutSection";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface PropertiesLayoutSectionProps extends Omit<DefaultPropertiesLayoutSectionProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultPropertiesLayoutSectionProps altogether and have
// total control over the props for your component.
export interface PropertiesLayoutSectionProps
  extends DefaultPropertiesLayoutSectionProps {
  node?: any;
  onUpdate?: (newProps: any) => void;
}

function PropertiesLayoutSection_(
  props: PropertiesLayoutSectionProps,
  ref: HTMLElementRefOf<"div">
) {
  const { node, onUpdate, ...rest } = props;
  
  // Extraire les propriétés de layout du nœud
  const layout = node?.props?.layout || {
    expansion: "none",
    flex: 1,
    padding: { l: 0, t: 0, r: 0, b: 0 },
    alignment: { slot: "center", x: 0, y: 0 },
  };

  // Propriétés spécifiques selon le type de widget
  const rowProps = node?.props?.rowProps;
  const columnProps = node?.props?.columnProps;

  const handleFlexChange = (value: number) => {
    if (onUpdate) {
      onUpdate({
        layout: { ...layout, flex: value }
      });
    }
  };

  const handlePaddingChange = (side: 'l' | 't' | 'r' | 'b', value: number) => {
    if (onUpdate) {
      onUpdate({
        layout: { 
          ...layout, 
          padding: { ...layout.padding, [side]: value } 
        }
      });
    }
  };

  const handleAlignmentChange = (slot: string, x: number, y: number) => {
    if (onUpdate) {
      onUpdate({
        layout: { 
          ...layout, 
          alignment: { slot, x, y } 
        }
      });
    }
  };

  const handleRowPropsChange = (newRowProps: any) => {
    if (onUpdate && rowProps) {
      onUpdate({ rowProps: { ...rowProps, ...newRowProps } });
    }
  };

  const handleColumnPropsChange = (newColumnProps: any) => {
    if (onUpdate && columnProps) {
      onUpdate({ columnProps: { ...columnProps, ...newColumnProps } });
    }
  };

  return (
    <PlasmicPropertiesLayoutSection 
      frame148={{ ref }} 
      {...rest}
      overrides={{
        // Vous pouvez ajouter des overrides ici pour connecter les contrôles
        // aux gestionnaires d'événements
      }}
    />
  );
}

const PropertiesLayoutSection = React.forwardRef(PropertiesLayoutSection_);
export default PropertiesLayoutSection;
