/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 14Poat1Xo2MFaa35ZoCnqd

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariants_0Fkg4Ij0Mdq3 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 0Fkg4IJ0Mdq3/globalVariant
import {
  UnnamedGlobalGroupOfVariantsValue,
  useUnnamedGlobalGroupOfVariants
} from "./PlasmicGlobalVariant__UnnamedGlobalGroupOfVariants"; // plasmic-import: cQH84q-hFMlX/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariants_0Fkg4Ij0Mdq3,
  unnamedGlobalGroupOfVariants: useUnnamedGlobalGroupOfVariants
});
