/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 14Poat1Xo2MFaa35ZoCnqd
// Component: YqzTJ0hGgXg6

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 14Poat1Xo2MFaa35ZoCnqd/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 14Poat1Xo2MFaa35ZoCnqd/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 14Poat1Xo2MFaa35ZoCnqd/projectcss
import sty from "./PlasmicIconSelectionItem.module.css"; // plasmic-import: YqzTJ0hGgXg6/css

import DefaultExpansionSvgIcon from "./icons/PlasmicIcon__DefaultExpansionSvg"; // plasmic-import: zG2EMLXUU3hG/icon

createPlasmicElementProxy;

export type PlasmicIconSelectionItem__VariantMembers = {};
export type PlasmicIconSelectionItem__VariantsArgs = {};
type VariantPropType = keyof PlasmicIconSelectionItem__VariantsArgs;
export const PlasmicIconSelectionItem__VariantProps =
  new Array<VariantPropType>();

export type PlasmicIconSelectionItem__ArgsType = {
  icon?: React.ReactNode;
  selected?: boolean;
  selectable?: boolean;
};
type ArgPropType = keyof PlasmicIconSelectionItem__ArgsType;
export const PlasmicIconSelectionItem__ArgProps = new Array<ArgPropType>(
  "icon",
  "selected",
  "selectable"
);

export type PlasmicIconSelectionItem__OverridesType = {
  root?: Flex__<"div">;
};

export interface DefaultIconSelectionItemProps {
  icon?: React.ReactNode;
  selected?: boolean;
  selectable?: boolean;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicIconSelectionItem__RenderFunc(props: {
  variants: PlasmicIconSelectionItem__VariantsArgs;
  args: PlasmicIconSelectionItem__ArgsType;
  overrides: PlasmicIconSelectionItem__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          selected: false,
          selectable: true
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      {renderPlasmicSlot({
        defaultContents: (
          <DefaultExpansionSvgIcon
            className={classNames(projectcss.all, sty.svg__qDfiq)}
            role={"img"}
          />
        ),

        value: args.icon
      })}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicIconSelectionItem__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicIconSelectionItem__VariantsArgs;
    args?: PlasmicIconSelectionItem__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicIconSelectionItem__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicIconSelectionItem__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicIconSelectionItem__ArgProps,
          internalVariantPropNames: PlasmicIconSelectionItem__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicIconSelectionItem__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicIconSelectionItem";
  } else {
    func.displayName = `PlasmicIconSelectionItem.${nodeName}`;
  }
  return func;
}

export const PlasmicIconSelectionItem = Object.assign(
  // Top-level PlasmicIconSelectionItem renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicIconSelectionItem
    internalVariantProps: PlasmicIconSelectionItem__VariantProps,
    internalArgProps: PlasmicIconSelectionItem__ArgProps
  }
);

export default PlasmicIconSelectionItem;
/* prettier-ignore-end */
