/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 14Poat1Xo2MFaa35ZoCnqd
// Component: 1T_9MyAFtbND

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 14Poat1Xo2MFaa35ZoCnqd/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 14Poat1Xo2MFaa35ZoCnqd/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 14Poat1Xo2MFaa35ZoCnqd/projectcss
import sty from "./PlasmicIconButtonSelectProperty.module.css"; // plasmic-import: 1T_9MyAFtbND/css

import SidebarLeftIcon from "./icons/PlasmicIcon__SidebarLeft"; // plasmic-import: 33tkUsgvZnao/icon

createPlasmicElementProxy;

export type PlasmicIconButtonSelectProperty__VariantMembers = {
  selected2: "selected2";
};
export type PlasmicIconButtonSelectProperty__VariantsArgs = {
  selected2?: SingleBooleanChoiceArg<"selected2">;
};
type VariantPropType = keyof PlasmicIconButtonSelectProperty__VariantsArgs;
export const PlasmicIconButtonSelectProperty__VariantProps =
  new Array<VariantPropType>("selected2");

export type PlasmicIconButtonSelectProperty__ArgsType = {
  iconSelected?: React.ReactNode;
  onclick?: () => void;
};
type ArgPropType = keyof PlasmicIconButtonSelectProperty__ArgsType;
export const PlasmicIconButtonSelectProperty__ArgProps = new Array<ArgPropType>(
  "iconSelected",
  "onclick"
);

export type PlasmicIconButtonSelectProperty__OverridesType = {
  root?: Flex__<"div">;
};

export interface DefaultIconButtonSelectPropertyProps {
  iconSelected?: React.ReactNode;
  onclick?: () => void;
  selected2?: SingleBooleanChoiceArg<"selected2">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicIconButtonSelectProperty__RenderFunc(props: {
  variants: PlasmicIconButtonSelectProperty__VariantsArgs;
  args: PlasmicIconButtonSelectProperty__ArgsType;
  overrides: PlasmicIconButtonSelectProperty__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "selected2",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.selected2
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        { [sty.rootselected2]: hasVariant($state, "selected2", "selected2") }
      )}
      onClick={async event => {
        const $steps = {};

        $steps["runOnclick"] = true
          ? (() => {
              const actionArgs = { eventRef: $props["onclick"] };
              return (({ eventRef, args }) => {
                return eventRef?.(...(args ?? []));
              })?.apply(null, [actionArgs]);
            })()
          : undefined;
        if (
          $steps["runOnclick"] != null &&
          typeof $steps["runOnclick"] === "object" &&
          typeof $steps["runOnclick"].then === "function"
        ) {
          $steps["runOnclick"] = await $steps["runOnclick"];
        }
      }}
    >
      {renderPlasmicSlot({
        defaultContents: (
          <SidebarLeftIcon
            className={classNames(projectcss.all, sty.svg__sVy7B)}
            role={"img"}
          />
        ),

        value: args.iconSelected
      })}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicIconButtonSelectProperty__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicIconButtonSelectProperty__VariantsArgs;
    args?: PlasmicIconButtonSelectProperty__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicIconButtonSelectProperty__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicIconButtonSelectProperty__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicIconButtonSelectProperty__ArgProps,
          internalVariantPropNames:
            PlasmicIconButtonSelectProperty__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicIconButtonSelectProperty__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicIconButtonSelectProperty";
  } else {
    func.displayName = `PlasmicIconButtonSelectProperty.${nodeName}`;
  }
  return func;
}

export const PlasmicIconButtonSelectProperty = Object.assign(
  // Top-level PlasmicIconButtonSelectProperty renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicIconButtonSelectProperty
    internalVariantProps: PlasmicIconButtonSelectProperty__VariantProps,
    internalArgProps: PlasmicIconButtonSelectProperty__ArgProps
  }
);

export default PlasmicIconButtonSelectProperty;
/* prettier-ignore-end */
