/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 14Poat1Xo2MFaa35ZoCnqd
// Component: bklbrvjs8_3B

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { BaseDialogTrigger } from "@plasmicpkgs/react-aria/skinny/registerDialogTrigger";
import { BasePopover } from "@plasmicpkgs/react-aria/skinny/registerPopover";
import OverlayArrow from "../../OverlayArrow"; // plasmic-import: oSh0nPygqs8l/component
import { BaseDialog } from "@plasmicpkgs/react-aria/skinny/registerDialog";
import AddWidgetSelection from "../../AddWidgetSelection"; // plasmic-import: pvtNa1_sMQiD/component
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 14Poat1Xo2MFaa35ZoCnqd/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 14Poat1Xo2MFaa35ZoCnqd/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 14Poat1Xo2MFaa35ZoCnqd/projectcss
import sty from "./PlasmicPopUpAddWidget.module.css"; // plasmic-import: bklbrvjs8_3B/css

import Plus1512SvgrepoComSvgIcon from "./icons/PlasmicIcon__Plus1512SvgrepoComSvg"; // plasmic-import: fu4dAXU-Gy_l/icon

createPlasmicElementProxy;

export type PlasmicPopUpAddWidget__VariantMembers = {};
export type PlasmicPopUpAddWidget__VariantsArgs = {};
type VariantPropType = keyof PlasmicPopUpAddWidget__VariantsArgs;
export const PlasmicPopUpAddWidget__VariantProps = new Array<VariantPropType>();

export type PlasmicPopUpAddWidget__ArgsType = {
  isOpen?: boolean;
  shouldFlip?: boolean;
  offset?: number;
  onOpenChange?: (val: boolean) => void;
  showArrow?: boolean;
  placement?: "top" | "bottom" | "start" | "end" | "left" | "right";
  selectWidgetAction?: (choosedWidget: any) => void;
  trigger?: React.ReactNode;
  children?: React.ReactNode;
};
type ArgPropType = keyof PlasmicPopUpAddWidget__ArgsType;
export const PlasmicPopUpAddWidget__ArgProps = new Array<ArgPropType>(
  "isOpen",
  "shouldFlip",
  "offset",
  "onOpenChange",
  "showArrow",
  "placement",
  "selectWidgetAction",
  "trigger",
  "children"
);

export type PlasmicPopUpAddWidget__OverridesType = {
  ariaDialogTrigger?: Flex__<typeof BaseDialogTrigger>;
  ariaPopover?: Flex__<typeof BasePopover>;
  overlayArrow?: Flex__<typeof OverlayArrow>;
  ariaDialog?: Flex__<typeof BaseDialog>;
};

export interface DefaultPopUpAddWidgetProps {
  isOpen?: boolean;
  shouldFlip?: boolean;
  offset?: number;
  onOpenChange?: (val: boolean) => void;
  showArrow?: boolean;
  placement?: "top" | "bottom" | "start" | "end" | "left" | "right";
  selectWidgetAction?: (choosedWidget: any) => void;
  trigger?: React.ReactNode;
  children?: React.ReactNode;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPopUpAddWidget__RenderFunc(props: {
  variants: PlasmicPopUpAddWidget__VariantsArgs;
  args: PlasmicPopUpAddWidget__ArgsType;
  overrides: PlasmicPopUpAddWidget__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          shouldFlip: true,
          offset: 12,
          placement: "bottom"
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "ariaDialogTrigger.isOpen",
        type: "writable",
        variableType: "boolean",

        valueProp: "isOpen",
        onChangeProp: "onOpenChange"
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <BaseDialogTrigger
      data-plasmic-name={"ariaDialogTrigger"}
      data-plasmic-override={overrides.ariaDialogTrigger}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "__wab_instance",
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.ariaDialogTrigger
      )}
      dialog={
        <BasePopover
          data-plasmic-name={"ariaPopover"}
          data-plasmic-override={overrides.ariaPopover}
          className={classNames("__wab_instance", sty.ariaPopover)}
          matchTriggerWidth={true}
          offset={args.offset}
          placement={args.placement}
          resetClassName={classNames(
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames
          )}
          shouldFlip={args.shouldFlip}
        >
          {$props.showArrow ? (
            <OverlayArrow
              data-plasmic-name={"overlayArrow"}
              data-plasmic-override={overrides.overlayArrow}
              className={classNames("__wab_instance", sty.overlayArrow)}
            />
          ) : null}
          <BaseDialog
            data-plasmic-name={"ariaDialog"}
            data-plasmic-override={overrides.ariaDialog}
            className={classNames("__wab_instance", sty.ariaDialog)}
          >
            {renderPlasmicSlot({
              defaultContents: (
                <AddWidgetSelection
                  className={classNames(
                    "__wab_instance",
                    sty.addWidgetSelection___6UhRa
                  )}
                />
              ),

              value: args.children
            })}
          </BaseDialog>
        </BasePopover>
      }
      isOpen={generateStateValueProp($state, ["ariaDialogTrigger", "isOpen"])}
      onOpenChange={async (...eventArgs: any) => {
        generateStateOnChangeProp($state, [
          "ariaDialogTrigger",
          "isOpen"
        ]).apply(null, eventArgs);
      }}
      trigger={renderPlasmicSlot({
        defaultContents: (
          <div className={classNames(projectcss.all, sty.freeBox___61Yiu)}>
            <Plus1512SvgrepoComSvgIcon
              className={classNames(projectcss.all, sty.svg__fcM)}
              role={"img"}
            />
          </div>
        ),
        value: args.trigger
      })}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  ariaDialogTrigger: [
    "ariaDialogTrigger",
    "ariaPopover",
    "overlayArrow",
    "ariaDialog"
  ],
  ariaPopover: ["ariaPopover", "overlayArrow", "ariaDialog"],
  overlayArrow: ["overlayArrow"],
  ariaDialog: ["ariaDialog"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  ariaDialogTrigger: typeof BaseDialogTrigger;
  ariaPopover: typeof BasePopover;
  overlayArrow: typeof OverlayArrow;
  ariaDialog: typeof BaseDialog;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPopUpAddWidget__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPopUpAddWidget__VariantsArgs;
    args?: PlasmicPopUpAddWidget__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPopUpAddWidget__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicPopUpAddWidget__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPopUpAddWidget__ArgProps,
          internalVariantPropNames: PlasmicPopUpAddWidget__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPopUpAddWidget__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "ariaDialogTrigger") {
    func.displayName = "PlasmicPopUpAddWidget";
  } else {
    func.displayName = `PlasmicPopUpAddWidget.${nodeName}`;
  }
  return func;
}

export const PlasmicPopUpAddWidget = Object.assign(
  // Top-level PlasmicPopUpAddWidget renders the root element
  makeNodeComponent("ariaDialogTrigger"),
  {
    // Helper components rendering sub-elements
    ariaPopover: makeNodeComponent("ariaPopover"),
    overlayArrow: makeNodeComponent("overlayArrow"),
    ariaDialog: makeNodeComponent("ariaDialog"),

    // Metadata about props expected for PlasmicPopUpAddWidget
    internalVariantProps: PlasmicPopUpAddWidget__VariantProps,
    internalArgProps: PlasmicPopUpAddWidget__ArgProps
  }
);

export default PlasmicPopUpAddWidget;
/* prettier-ignore-end */
